kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  selfLink: /apis/image.openshift.io/v1/namespaces/f00029-tools/imagestreams/angular-app
  name: nrpti-api
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: image.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:build': {}
  namespace: f00029-tools
  labels:
    app: nrpti-api
    build: nrpti-api
spec:
  lookupPolicy:
    local: false