apiVersion: v1
kind: Template
metadata:
  name: cronjob-template
  annotations:
    description: 'Template for job that curls your api'
    tags: 'cronjob'
parameters:
  - name: CRON_SCHEDULE
    description: 'Cron-like schedule expression. Default: Once every day at 12:00 AM'
    value: '0 0 * * *'
  - name: CRON_NAME
    decription: 'Name of the cronjob container.'
    value: 'nrpti-cronjob'
objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: ${CRON_NAME}
    spec:
      schedule: ${CRON_SCHEDULE}
      concurrencyPolicy: Forbid
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: ${CRON_NAME}
                  image: 'docker-registry.default.svc:5000/openshift/base-centos7:latest'
                  command:
                    - 'bash'
                    - '-c'
                    - >-
                      echo -e "-------- STARTING CRON --------\n"
                      echo -e "-------- GETTING ACCESS TOKEN --------\n"

                      TOKEN=$(curl -X POST "${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token" \
                        -H "Content-Type: application/x-www-form-urlencoded" \
                        -d "username=${KEYCLOAK_USERNAME}" \
                        -d "password=${KEYCLOAK_PASSWORD}" \
                        -d "grant_type=password" \
                        -d "client_id=${KEYCLOAK_CLIENT_ID}" \
                        -d "client_secret=${KEYCLOAK_CLIENT_SECRET}" | python -c "import sys, json; print json.load(sys.stdin)['access_token']")
                      
                      echo -e "-------- UPDATING SUBSETS --------\n"
                      
                      echo -e "Updating issuedTo subset\n"

                      curl -H "Authorization: Bearer ${TOKEN}" \
                        -H "Content-Type: application/json" \
                        -d '{"taskType":"updateMaterializedView", "materializedViewSubset":"issuedTo"}' \
                        ${NRPTI_API_URL}/task
                      
                      echo -e "Updating location subset\n"

                      curl -H "Authorization: Bearer ${TOKEN}" \
                        -H "Content-Type: application/json" \
                        -d '{"taskType":"updateMaterializedView", "materializedViewSubset":"location"}' \
                        ${NRPTI_API_URL}/task
                      
                      echo -e "Updating recordNameSubset subset\n"

                      curl -H "Authorization: Bearer ${TOKEN}" \
                        -H "Content-Type: application/json" \
                        -d '{"taskType":"updateMaterializedView", "materializedViewSubset":"recordNameSubset"}' \
                        ${NRPTI_API_URL}/task
                      
                      echo -e "Updating descriptionSummary subset\n"

                      curl -H "Authorization: Bearer ${TOKEN}" \
                        -H "Content-Type: application/json" \
                        -d '{"taskType":"updateMaterializedView", "materializedViewSubset":"descriptionSummary"}' \
                        ${NRPTI_API_URL}/task

                      echo -e "-------- RUNNING IMPORTERS --------\n"

                      echo -e "Importing EPIC\n"

                      curl -H "Authorization: Bearer ${TOKEN}" \
                        -H "Content-Type: application/json" \
                        -d '{"taskType":"import", "dataSourceType":"epic"}' \
                        ${NRPTI_API_URL}/task

                      echo -e "Importing CORE\n"

                      curl -H "Authorization: Bearer ${TOKEN}" \
                        -H "Content-Type: application/json" \
                        -d '{"taskType":"import", "dataSourceType":"core"}' \
                        ${NRPTI_API_URL}/task
                      
                        echo -e "-------- CRON COMPLETE --------\n"
                  resources:
                  limits:
                    cpu: 500m
                    memory: 2Gi
                  requests:
                    cpu: 100m
                    memory: 512Mi
                  env:
                    - name: KEYCLOAK_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: nrpti-cron-secrets
                          key: KEYCLOAK_PASSWORD
                    - name: KEYCLOAK_CLIENT_ID
                      valueFrom:
                        secretKeyRef:
                          name: nrpti-cron-secrets
                          key: KEYCLOAK_CLIENT_ID
                    - name: KEYCLOAK_CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: nrpti-cron-secrets
                          key: KEYCLOAK_CLIENT_SECRET
                    - name: KEYCLOAK_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: nrpti-cron-secrets
                          key: KEYCLOAK_USERNAME
                    - name: KEYCLOAK_URL
                      valueFrom:
                        secretKeyRef:
                          name: nrpti-cron-secrets
                          key: KEYCLOAK_URL
                    - name: KEYCLOAK_REALM
                      valueFrom:
                        secretKeyRef:
                          name: nrpti-cron-secrets
                          key: KEYCLOAK_REALM
                    - name: NRPTI_API_URL
                      valueFrom:
                        secretKeyRef:
                          name: nrpti-cron-secrets
                          key: NRPTI_API_URL
              restartPolicy: Never