apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: ${NAME}
      labels:
        app: ${GROUP_NAME}
        build: ${NAME}-build
    spec:
      lookupPolicy:
        local: false
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${GROUP_NAME}
        build: ${NAME}-build
      name: ${NAME}
    spec:
      completionDeadlineSeconds: 300
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:latest
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
      runPolicy: Serial
      source:
        contextDir: api
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: ${SOURCE_IMAGE_NAMESPACE}
            name: ${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
      successfulBuildsHistoryLimit: 5
      triggers:
        - type: ConfigChange
parameters:
  - description: A name used for all objects
    displayName: Name
    name: NAME
    required: true
    value: nrpti-api
  - description: A name used for all objects in the build or deploy group
    displayName: Group name
    name: GROUP_NAME
    required: true
    value: nrpti
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: https://github.com/bcgov/NRPTI
  - name: SOURCE_REPOSITORY_REF
    required: true
    value: master
  - name: SOURCE_IMAGE_NAME
    required: true
    value: nodejs
  - name: SOURCE_IMAGE_TAG
    required: true
    value: "10"
  - name: SOURCE_IMAGE_NAMESPACE
    required: true
    value: openshift
