# Base image for the container
FROM node:18.19-alpine

# Set the working directory
WORKDIR /app/

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . /app

# Build for production - clean, build library, and build public-nrpti
RUN npm run build:library && \
    cd dist/nrpti-angular-components && \
    npm link && \
    cd /app && \
    npm link nrpti-angular-components && \
    npm run build:app:public-nrced

# Install a simple server to serve static files
RUN npm install -g serve

# Make entrypoint script for public-nrpti
COPY entrypoint-public-nrpti.sh /app/entrypoint-public-nrpti.sh
RUN chmod +x /app/entrypoint-public-nrpti.sh

# Expose port 80
EXPOSE 80

# Use the entrypoint script
CMD ["/app/entrypoint-public-nrpti.sh"] 