apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${GROUP_NAME}
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: ${GROUP_NAME}
        deploymentconfig: ${NAME}
      type: ClusterIP
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: ${NAME}
      labels:
        app: ${GROUP_NAME}
    spec:
      host: ${NAME}-${Host}
      to:
        kind: Service
        name: ${NAME}
        weight: 100
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: ${NAME}
        app.kubernetes.io/part-of: frontend
        app.openshift.io/runtime: nodejs
        role: frontend
      name: ${NAME}
      namespace: f00029-${ENVIRONMENT}
      annotations:
        image.openshift.io/triggers: '[{"from": {"kind": "ImageStreamTag", "name":
          "nrpti:latest", "namespace": "f00029-tools"}, "fieldPath":
          "spec.template.spec.containers[?(@.name==\"nrpti\")].image", "paused":
          false}]'
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: ${NAME}
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: nrpti
            deploymentconfig: nrpti
            role: frontend
        spec:
          containers:
            - env:
                - name: RealIpFrom
                  value: 10.97.0.0/16
                - name: AdditionalRealIpFromRules
                - name: IpFilterRules
                  value: "#allow all; deny all;"
                - name: CONFIG_ENDPOINT_HOST
                  value: NRPTI_API_SERVICE_HOST
                - name: CONFIG_ENDPOINT_PORT
                  value: NRPTI_API_SERVICE_PORT
                - name: ENVIRONMENT
                  value: ${ENVIRONMENT}
              image: image-registry.openshift-image-registry.svc:5000/${RUNTIME_IMAGE_NAMESPACE}/${NAME}:${RUNTIME_IMAGE_TAG}
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 60
              name: nrpti
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 60
              resources:
                limits:
                  cpu: 250m
                  memory: 150Mi
                requests:
                  cpu: 10m
                  memory: 50Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
parameters:
  - description: A name used for all objects
    displayName: Name
    name: NAME
    required: true
    value: nrpti
  - description: A name used for all objects in the build or deploy group
    displayName: Group name
    name: GROUP_NAME
    required: true
    value: nrpti
  - name: RUNTIME_IMAGE_NAMESPACE
    required: true
    value: f00029-tools
  - name: RUNTIME_IMAGE_TAG
    required: true
    value: latest
  - name: Host
    value: f00029-dev.apps.silver.devops.gov.bc.ca
  - name: ENVIRONMENT
    value: dev
