apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${GROUP_NAME}
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: ${GROUP_NAME}
        deploymentconfig: ${NAME}
      type: ClusterIP
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: ${NAME}
      labels:
        app: ${GROUP_NAME}
    spec:
      host: ${NAME}-${Host}
      to:
        kind: Service
        name: ${NAME}
        weight: 100
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: ${NAME}
      labels:
        app: ${GROUP_NAME}
        role: frontend
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              namespace: ${RUNTIME_IMAGE_NAMESPACE}
              name: ${RUNTIME_IMAGE_NAME}:${RUNTIME_IMAGE_TAG}
        - type: ConfigChange
      replicas: 1
      revisionHistoryLimit: 5
      test: false
      selector:
        app: ${GROUP_NAME}
        deploymentconfig: ${NAME}
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: ${GROUP_NAME}
            deploymentconfig: ${NAME}
            role: frontend
        spec:
          containers:
            - name: ${NAME}
              image: image-registry.openshift-image-registry.svc:5000/${RUNTIME_IMAGE_NAMESPACE}/${RUNTIME_IMAGE_NAME}:${RUNTIME_IMAGE_TAG}
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: RealIpFrom
                  value: 10.97.0.0/16
                - name: AdditionalRealIpFromRules
                - name: IpFilterRules
                  value: "#allow all; deny all;"
                - name: CONFIG_ENDPOINT_HOST
                  value: NRPTI_API_SERVICE_HOST
                - name: CONFIG_ENDPOINT_PORT
                  value: NRPTI_API_SERVICE_PORT
              resources:
                limits:
                  cpu: 250m
                  memory: 250Mi
                requests:
                  cpu: 10m
                  memory: 50Mi
              livenessProbe:
                httpGet:
                  path: "/"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: "/"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
parameters:
  - description: A name used for all objects
    displayName: Name
    name: NAME
    required: true
    value: nrced
  - description: A name used for all objects in the build or deploy group
    displayName: Group name
    name: GROUP_NAME
    required: true
    value: nrpti
  - name: RUNTIME_IMAGE_NAMESPACE
    required: true
    value: f00029-tools
  - name: RUNTIME_IMAGE_NAME
    required: true
    value: public-nrced
  - name: RUNTIME_IMAGE_TAG
    required: true
    value: latest
  - name: Host
    value: f00029-dev.apps.silver.devops.gov.bc.ca
