version: "3.7"
services:
  #############################################################################################
  ###                                       Mongo                                           ###
  #############################################################################################
  mongo:
    image: mongo:3.6
    container_name: nrpti-mongo
    tty: true
    restart: always
    volumes: 
      - ./mongoSeed/init:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    networks:
      - nrpti
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo nrpti-dev -u ${MONGO_USERNAME:-nrpti-admin} -p ${MONGO_PASSWORD:-nrpti-admin} --quiet | grep 1
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 120s
  #############################################################################################
  ###                                         API                                           ###
  #############################################################################################
  api:
    container_name: nrpti-api
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - nrpti
    environment:
      - MONGODB_SERVICE_HOST=mongo
      - SSO_ISSUER=https://dev.loginproxy.gov.bc.ca/auth/realms/standard
      - SSO_JWKSURI=https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs
      - KEYCLOAK_CLIENT_ID=nrpti-4869
      - KEYCLOAK_URL=https://dev.loginproxy.gov.bc.ca/auth
      - KEYCLOAK_REALM=standard
    ports: 
      - 3000:3000
    # healthcheck:
    #   test: curl localhost:${PORT:-3000}/api/health | grep 'API is healthy and ready'
    #   interval: 20s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy

  # This works but it's not great for security reasons apparently
  # See this: https://v17.angular.io/guide/deployment
  ############################################################################################
  ###                                        ANGULAR ADMIN (NRPTI)                                 ###
  ############################################################################################
  admin-nrpti:
    container_name: admin-nrpti
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      api:
        condition: service_started
    environment:
      - DEBUG_MODE=false
      - ENVIRONMENT=dev
      - API_LOCATION=http://localhost:3000
      - API_PATH=/api
      - API_PUBLIC_PATH=/api/public
      - KEYCLOAK_CLIENT_ID=nrpti-4869
      - KEYCLOAK_URL=https://dev.loginproxy.gov.bc.ca/auth
      - KEYCLOAK_REALM=standard
      - KEYCLOAK_ENABLED=true
      - APPLICATION=NRPTI
     ############################################################################################
  ###                                        ANGULAR PUBLIC (NRCED)                                ###
  ############################################################################################
  public-nrpti:
    container_name: public-nrpti
    build:
      context: ./angular
      dockerfile: Dockerfile-public-nrpti
    ports:
      - 4400:4400
    depends_on:
      api:
        condition: service_started
    environment:
      - DEBUG_MODE=false
      - ENVIRONMENT=dev
      - API_LOCATION=http://localhost:3000
      - API_PATH=/api
      - API_PUBLIC_PATH=/api/public
      - FEATURE_FLAG_NRIS_EMLI_IMPORTER=true
      - HOST_URL=http://localhost:4200
      - APPLICATION=NRCED

#############################################################################################
###                                       Network                                         ###
#############################################################################################
networks:
  nrpti:
    driver: "bridge"
