apiVersion: template.openshift.io/v1
kind: Template
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${OUTPUT_IMAGE_TAG}
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 2Gi
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Docker
        dockerStrategy:
          pullSecret:
            name: artifactory-pull
          from:
            kind: DockerImage
            name: ${BASE_IMAGE_FOR_BUILD}
          dockerfilePath: ${DOCKER_FILE_PATH}
      postCommit: {}
      source:
        type: Git
        git:
          uri: ${GIT_REPO_URL}
          ref: ${GIT_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      triggers:
        - type: ConfigChange
      runPolicy: Serial
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the resources.  Use 'backup-{database name}' depending on your database provider
    required: true
    value: postgres-backup
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description: The URL to your GIT repo.
    required: true
    value: https://github.com/BCDevOps/backup-container.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: master
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: "/docker"
  - name: DOCKER_FILE_PATH
    displayName: Docker File
    description:
      The path and file of the docker file defining the build.  Choose either
      'Dockerfile' for Postgres builds or 'Dockerfile_Mongo' for MongoDB builds or 'Dockerfile_MSSQL'
      for MSSQL builds.
    required: false
    value: Dockerfile
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: v1
  - name: BASE_IMAGE_FOR_BUILD
    displayName: FROM Image Tag
    description:
      Base image to build from.  Docker creds or Artificatory setup may be
      needed to alleviate docker rate-limiting
    required: true
    value: docker-remote.artifacts.developer.gov.bc.ca/centos/postgresql-12-centos7:20200917-804ef01
