name: .Deploys

on:
  workflow_call:
    inputs:
      ### Required
      # Nothing! Only `secrets: inherit` is required

      ### Typical / recommended
      environment:
        description: GitHub/OpenShift environment; usually PR number, test or prod
        default: ''
        type: string
      tag:
        description: Container tag; usually PR number
        default: ${{ github.event.number }}
        type: string
      target:
        description: Deployment target; usually PR number, test or prod
        default: ${{ github.event.number }}
        type: string
      triggers:
        description: List of directories to trigger the deployment
        default: ''
        type: string

      ### Optional / per-environment
      db-pvc-size:
        description: Database PVC size; e.g. 1Gi
        default: "1.8Gi"
        type: string
      db-memory-request:
        description: Database memory request; e.g. 2Gi
        default: "512Mi"
        type: string
      max-replicas:
        description: Maximum replicas for api, frontend
        default: 5
        type: number
      min-replicas:
        description: Minimum replicas for backend, frontend and oracle-api
        default: 3
        type: number

    outputs:
      triggered:
        description: Has a deployment been triggered?
        value: ${{ jobs.init.outputs.triggered }}

permissions: {}

jobs:
  init:
    name: Deploy (init)
    environment: ${{ inputs.environment }}
    outputs:
      fam-modded-zone: ${{ steps.fam-modded-zone.outputs.fam-modded-zone }}
      triggered: ${{ steps.trigger.outputs.triggered }}
    runs-on: ubuntu-24.04
    steps:
      - name: FAM routing
        id: fam-modded-zone
        run: |
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            echo "fam-modded-zone=$(( ${{ inputs.target }} % 50 ))" >> $GITHUB_OUTPUT
          else
            echo "fam-modded-zone=${{ inputs.target }}" >> $GITHUB_OUTPUT
          fi

      - name: OpenShift Init
        id: trigger
        uses: bcgov/action-deployer-openshift@v4.0.0
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          file: common/openshift.init.yml
          overwrite: true
          parameters:
            # -p ZONE=${{ inputs.target }}
            # -p DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
            # -p FORESTCLIENTAPI_KEY='${{ secrets.FORESTCLIENTAPI_KEY }}'
            # -p ORACLE_PASSWORD='${{ secrets.ORACLE_PASSWORD }}'
            # -p ORACLE_SERVICE='${{ vars.ORACLE_SERVICE }}'
            # -p ORACLE_USER='${{ vars.ORACLE_USER }}'
            # -p ORACLE_CERT_SECRET='${{ secrets.ORACLE_CERT_SECRET }}'
            # -p ORACLE_HOST='${{ vars.ORACLE_HOST }}'
            # -p S3_BUCKET='${{ vars.S3_BUCKET }}'
            # -p S3_ENDPOINT='${{ vars.S3_ENDPOINT }}'
            # -p S3_USER='${{ vars.S3_USER }}'
            # -p S3_PASSWORD='${{ secrets.S3_PASSWORD }}'
            # -p VITE_USER_POOLS_WEB_CLIENT_ID=${{ secrets.VITE_USER_POOLS_WEB_CLIENT_ID }}
          triggers: ${{ inputs.triggers }}

      - name: Database
        uses: bcgov/action-deployer-openshift@v4.0.0
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          file: common/openshift.database.yml
          overwrite: false
          parameters:
            -p ZONE=${{ inputs.target }}
            -p DB_PVC_SIZE=${{ inputs.db-pvc-size }}
            -p MEMORY_REQUEST=${{ inputs.db-memory-request }}
          triggers: ${{ inputs.triggers }}

  deploy:
    name: Deploy
    environment: ${{ inputs.environment }}
    needs: [init]
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      matrix:
        name: [backend, frontend, oracle-api]
        include:
          - name: backend
          #   parameters:
          #     -p AWS_COGNITO_ISSUER_URI=https://cognito-idp.ca-central-1.amazonaws.com/${{ vars.VITE_USER_POOLS_ID }}
          # - name: frontend
          #   parameters:
          #     -p FAM_MODDED_ZONE=${{ needs.init.outputs.fam-modded-zone }}
          #     -p VITE_SPAR_BUILD_VERSION=snapshot-${{ inputs.target }}
          #     -p VITE_USER_POOLS_ID=${{ vars.VITE_USER_POOLS_ID }}
          # - name: oracle-api
          #   parameters:
          #     -p AWS_COGNITO_ISSUER_URI=https://cognito-idp.ca-central-1.amazonaws.com/${{ vars.VITE_USER_POOLS_ID }}
    steps:
      - uses: bcgov/action-deployer-openshift@v4.0.0
        id: deploys
        with:
          file: ${{ matrix.name }}/openshift.deploy.yml
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: false
          parameters:
            -p TAG=${{ inputs.tag }}
            -p ZONE=${{ inputs.target }}
            -p MIN_REPLICAS=${{ inputs.min-replicas }}
            -p MAX_REPLICAS=${{ inputs.max-replicas }}
            ${{ matrix.parameters }}
          triggers: ${{ inputs.triggers }}