name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  # https://github.com/bcgov/action-builder-ghcr
  builds:
    name: Builds
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - package: api
            directory: api
            dockerfile: Dockerfile
          - package: admin-nrpti
            directory: angular
            dockerfile: Dockerfile
          - package: public-nrpti
            directory: angular
            dockerfile: Dockerfile-public-nrpti
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@ace71f7a527ca6fc43c15c7806314be5a4579d2c # v2.3.0
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          build_context: ${{ matrix.directory }}
          build_file: ${{ matrix.directory }}/${{ matrix.dockerfile }}
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('${{ matrix.directory }}/')

  # https://github.com/bcgov/action-deploy-ghcr
  deploys:
    name: Deploys (${{ github.event.number }})
    needs: [builds]
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      triggers: ('api/' 'angular/')