name: Openshift Test Deployment on Demand
on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Openshift Token'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to OpenShift
        run: |
          oc login --token=$TOKEN --server=https://api.silver.devops.gov.bc.ca:6443
        env:
          TOKEN: ${{ inputs.token }}
      
      - name: Set OpenShift project
        run: |
          oc project f00029-tools
          
      - name: Tag nrpti-api
        run: |
          oc tag nrpti-api:test nrpti-api:test-backup
          oc tag nrpti-api:latest nrpti-api:test
          
      - name: Tag nrpti
        run: |
          oc tag nrpti:test nrpti:test-backup
          oc tag nrpti:latest nrpti:test
          
      - name: Tag public-nrced
        run: |
          oc tag public-nrced:test public-nrced:test-backup
          oc tag public-nrced:latest public-nrced:test

      - name: Completion message
        run: |
          echo "Test deployment completed"
